### ISSUE TITLE
ValueError: Requested crop size (512, 512) is larger than the image size (384, 384)

### ISSUE THREAD

**Issue by themoongodyue** [Z-Zheng/ChangeStar#4]
Traceback (most recent call last):
  File "./train_sup_change.py", line 48, in <module>
    blob = trainer.run(after_construct_launcher_callbacks=[register_evaluate_fn])
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/ever/api/trainer/th_amp_ddp_trainer.py", line 117, in run
    test_data_loader=kw_dataloader['testdata_loader'])
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/ever/core/launcher.py", line 232, in train_by_config
    signal_loss_dict = self.train_iters(train_data_loader, test_data_loader=test_data_loader, **config)
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/ever/core/launcher.py", line 174, in train_iters
    is_master=self._master)
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/ever/core/iterator.py", line 30, in next
    data = next(self._iterator)
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 218, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/yujianzhi/tem/ChangeStar-master/data/levir_cd/dataset.py", line 30, in __getitem__
    blob = self.transforms(**dict(image=imgs, mask=gt))
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/albumentations/core/composition.py", line 191, in __call__
    data = t(force_apply=force_apply, **data)
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 90, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 103, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/albumentations/augmentations/crops/transforms.py", line 48, in apply
    return F.random_crop(img, self.height, self.width, h_start, w_start)
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/albumentations/augmentations/crops/functional.py", line 28, in random_crop
    crop_height=crop_height, crop_width=crop_width, height=height, width=width
ValueError: Requested crop size (512, 512) is larger than the image size (384, 384)
Traceback (most recent call last):
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/yujianzhi/anaconda3/envs/CStar/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/yujianzhi/anaconda3/envs/CStar/bin/python', '-u', './train_sup_change.py', '--local_rank=0', '--config_path=levircd.r50_farseg_changestar_bisup', '--model_dir=./log/bisup-LEVIRCD/r50_farseg_changestar']' returned non-zero exit status 1.

it says：  ValueError: Requested crop size (512, 512) is larger than the image size (384, 384)
but my img is 512*512 exactly.

**Comment by Z-Zheng** [comment]
This error is caused by the image of size (384, 384).
It means that there is a 384x384 image in your dataset.
Maybe you can check it.

**Comment by themoongodyue** [comment]
i have checked my dataset
it remains to show the size of imgs are 512*512

**Comment by linjiaxing99** [comment]
Becasue there are RandomDiscreteScale before the RandomCrop,it will change the picture to 384*384

**Comment by linjiaxing99** [comment]
> i have checked my dataset it remains to show the size of imgs are 512*512

Becasue there are RandomDiscreteScale before the RandomCrop,it will change the picture to 384*384
