### ISSUE TITLE
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8

### ISSUE THREAD

**Issue by themoongodyue** [Z-Zheng/ChangeStar#5]
i have crazy,help me please

Traceback (most recent call last):
  File "./train_sup_change.py", line 48, in <module>
    blob = trainer.run(after_construct_launcher_callbacks=[register_evaluate_fn])
  File "/home/cy/miniconda3/envs/STAnet/lib/python3.8/site-packages/ever/api/trainer/th_amp_ddp_trainer.py", line 98, in run
    kwargs.update(dict(model=self.make_model()))
  File "/home/cy/miniconda3/envs/STAnet/lib/python3.8/site-packages/ever/api/trainer/th_amp_ddp_trainer.py", line 87, in make_model
    model = nn.parallel.DistributedDataParallel(
  File "/home/cy/miniconda3/envs/STAnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 496, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 31335) of binary: /home/cy/miniconda3/envs/STAnet/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed

**Comment by Z-Zheng** [comment]
Sorry, by this information you provided, I can't get why the problem happened.

In our testing environment, the training scripts both worked well.
PyTorch == 1.7.0
python == 3.7
cuda == 10.1
